using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

[Flags]
public enum COREWEBVIEW2_PDF_TOOLBAR_ITEMS
{
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_NONE = 0, // 0x0,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE = 1, // 0x1,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PRINT = 2, // 0x2,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE_AS = 4, // 0x4,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_IN = 8, // 0x8,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ZOOM_OUT = 16, // 0x10,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_ROTATE = 32, // 0x20,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FIT_PAGE = 64, // 0x40,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_LAYOUT = 128, // 0x80,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_BOOKMARKS = 256, // 0x100,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PAGE_SELECTOR = 512, // 0x200,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SEARCH = 1024, // 0x400,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_FULL_SCREEN = 2048, // 0x800,
    COREWEBVIEW2_PDF_TOOLBAR_ITEMS_MORE_SETTINGS = 4096, // 0x1000
}
