using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_PRINT_DUPLEX
{
    COREWEBVIEW2_PRINT_DUPLEX_DEFAULT,
    COREWEBVIEW2_PRINT_DUPLEX_ONE_SIDED,
    COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_LONG_EDGE,
    COREWEBVIEW2_PRINT_DUPLEX_TWO_SIDED_SHORT_EDGE
}
