using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL
{
    COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL_NORMAL,
    COREWEBVIEW2_MEMORY_USAGE_TARGET_LEVEL_LOW
}
