using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_PRINT_COLLATION
{
    COREWEBVIEW2_PRINT_COLLATION_DEFAULT,
    COREWEBVIEW2_PRINT_COLLATION_COLLATED,
    COREWEBVIEW2_PRINT_COLLATION_UNCOLLATED
}
