using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND
{
    COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_PAGE,
    COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_IMAGE,
    COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_SELECTED_TEXT,
    COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_AUDIO,
    COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_VIDEO
}
