using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_PREFERRED_COLOR_SCHEME
{
    COREWEBVIEW2_PREFERRED_COLOR_SCHEME_AUTO,
    COREWEBVIEW2_PREFERRED_COLOR_SCHEME_LIGHT,
    COREWEBVIEW2_PREFERRED_COLOR_SCHEME_DARK
}
