using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND
{
    COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND_NORMAL,
    COREWEBVIEW2_BROWSER_PROCESS_EXIT_KIND_FAILED
}
