using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

[Flags]
public enum COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS : uint
{
    COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_NONE = 0, // 0x0,
    COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_DOCUMENT = 1, // 0x1,
    COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SHARED_WORKER = 2, // 0x2,
    COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SERVICE_WORKER = 4, // 0x4,
    COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_ALL = 4294967295, // 0xFFFFFFFF
}
