using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_SCRIPT_DIALOG_KIND
{
    COREWEBVIEW2_SCRIPT_DIALOG_KIND_ALERT,
    COREWEBVIEW2_SCRIPT_DIALOG_KIND_CONFIRM,
    COREWEBVIEW2_SCRIPT_DIALOG_KIND_PROMPT,
    COREWEBVIEW2_SCRIPT_DIALOG_KIND_BEFOREUNLOAD
}
