using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

[Flags]
public enum COREWEBVIEW2_RELEASE_CHANNELS
{
    COREWEBVIEW2_RELEASE_CHANNELS_NONE = 0, // 0x0,
    COREWEBVIEW2_RELEASE_CHANNELS_STABLE = 1, // 0x1,
    COREWEBVIEW2_RELEASE_CHANNELS_BETA = 2, // 0x2,
    COREWEBVIEW2_RELEASE_CHANNELS_DEV = 4, // 0x4,
    COREWEBVIEW2_RELEASE_CHANNELS_CANARY = 8, // 0x8
}
