using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_NAVIGATION_KIND
{
    COREWEBVIEW2_NAVIGATION_KIND_RELOAD,
    COREWEBVIEW2_NAVIGATION_KIND_BACK_OR_FORWARD,
    COREWEBVIEW2_NAVIGATION_KIND_NEW_DOCUMENT
}
