using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT
{
    COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG,
    COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_JPEG
}
