using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_TRACKING_PREVENTION_LEVEL
{
    COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_NONE,
    COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BASIC,
    COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_BALANCED,
    COREWEBVIEW2_TRACKING_PREVENTION_LEVEL_STRICT
}
