using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_PRINT_COLOR_MODE
{
    COREWEBVIEW2_PRINT_COLOR_MODE_DEFAULT,
    COREWEBVIEW2_PRINT_COLOR_MODE_COLOR,
    COREWEBVIEW2_PRINT_COLOR_MODE_GRAYSCALE
}
