using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION
{
    COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_ALWAYS_ALLOW,
    COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_CANCEL,
    COREWEBVIEW2_SERVER_CERTIFICATE_ERROR_ACTION_DEFAULT
}
