using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND
{
    COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY,
    COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_ALLOW,
    COREWEBVIEW2_HOST_RESOURCE_ACCESS_KIND_DENY_CORS
}
