using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

[Flags]
public enum COREWEBVIEW2_BROWSING_DATA_KINDS
{
    COREWEBVIEW2_BROWSING_DATA_KINDS_FILE_SYSTEMS = 1, // 0x1,
    COREWEBVIEW2_BROWSING_DATA_KINDS_INDEXED_DB = 2, // 0x2,
    COREWEBVIEW2_BROWSING_DATA_KINDS_LOCAL_STORAGE = 4, // 0x4,
    COREWEBVIEW2_BROWSING_DATA_KINDS_WEB_SQL = 8, // 0x8,
    COREWEBVIEW2_BROWSING_DATA_KINDS_CACHE_STORAGE = 16, // 0x10,
    COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_DOM_STORAGE = 32, // 0x20,
    COREWEBVIEW2_BROWSING_DATA_KINDS_COOKIES = 64, // 0x40,
    COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_SITE = 128, // 0x80,
    COREWEBVIEW2_BROWSING_DATA_KINDS_DISK_CACHE = 256, // 0x100,
    COREWEBVIEW2_BROWSING_DATA_KINDS_DOWNLOAD_HISTORY = 512, // 0x200,
    COREWEBVIEW2_BROWSING_DATA_KINDS_GENERAL_AUTOFILL = 1024, // 0x400,
    COREWEBVIEW2_BROWSING_DATA_KINDS_PASSWORD_AUTOSAVE = 2048, // 0x800,
    COREWEBVIEW2_BROWSING_DATA_KINDS_BROWSING_HISTORY = 4096, // 0x1000,
    COREWEBVIEW2_BROWSING_DATA_KINDS_SETTINGS = 8192, // 0x2000,
    COREWEBVIEW2_BROWSING_DATA_KINDS_ALL_PROFILE = 16384, // 0x4000,
    COREWEBVIEW2_BROWSING_DATA_KINDS_SERVICE_WORKERS = 32768, // 0x8000
}
