using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_CLIENT_CERTIFICATE_KIND
{
    COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_SMART_CARD,
    COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_PIN,
    COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_OTHER
}
