using System;
using System.Runtime.InteropServices;

namespace Diga.WebView2.Interop;

public enum COREWEBVIEW2_PRINT_STATUS
{
    COREWEBVIEW2_PRINT_STATUS_SUCCEEDED,
    COREWEBVIEW2_PRINT_STATUS_PRINTER_UNAVAILABLE,
    COREWEBVIEW2_PRINT_STATUS_OTHER_ERROR
}
